zeebe:
  client:
    worker:
      defaultName: zeebe-simple-tasklist
      defaultType: io.camunda.zeebe:userTask
      threads: 2

      hazelcast:
        connection: localhost:5701
        connectionTimeout: PT30S

      tasklist:
        defaultTaskForm: /templates/default-task-form.html
        adminUsername: demo
        adminPassword: demo

    job.timeout: 2592000000 # 30 days
    broker.gateway-address: 127.0.0.1:26500
    security.plaintext: true

spring:

  datasource:
    url: jdbc:h2:~/zeebe-tasklist
    username: sa
    password:
    driverClassName: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

  mustache:
    prefix: classpath:/templates/
    suffix: .html
    expose-request-attributes: true

  data:
    web:
      pageable:
        default-page-size: 10

  main:
    allow-circular-references: true

server:
  port: 8081
  servlet:
    context-path: /
  allowedOriginsUrls: ""

logging:
  level:
    root: ERROR
    io.camunda: INFO
    io.zeebe.tasklist: DEBUG
    com.hazelcast: WARN

white-label:
  logo.path: img/logo.png
  custom:
    title: Zeebe Simple Tasklist
    css.path: css/custom.css
    js.path: js/custom.js